apiVersion: v1
kind: ConfigMap
metadata:
  name: business-hub-metadata
data:
  version: {{ .Chart.AppVersion | quote }}
  channel: "argocd"
  isAirgap: "unknown"
  deploymentName: "KNIME Business Hub"
