####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################
global:
  image:
    registry: "registry.hubdev.knime.com/knime-hub"
    pullSecretNames:
      - regcred

config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
        merge:
          metadata:
            annotations:
              argocd.argoproj.io/sync-options: Delete=false
  merge:
    accounts:
      AUTH:
        # The password is passed in via environment variable into nats, see below.
        users: [{ user: auth, password: << $AUTH_USER_PASSWORD >> }]
      KNIME:
        jetstream: enabled
      SYS: {}
    system_account: SYS
    authorization:
      auth_callout:
        # This is a public key. Static for now, a future improvement is to generate it randomly.
        # See https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_callout#setup-and-configuration.
        ## KNIME TODO: Add user overrides for all necessary keys/etc in this file.
        issuer: AB5IVC4NUYJDTRO2VF6OOP4MYIPPZZVTPHAIHRZOHQWUVY5AYQPC6QAK
        auth_users: [auth]
        account: AUTH
        # This is a public key. Static for now, a future improvement is to generate it randomly.
        # See https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_callout#setup-and-configuration.
        xkey: XAE75AQJF6QLK5BI4T2HPXRXQNSRAJBZVTE6XWV7NKDRAIQWHREC5EPH
container:
  env:
    # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    # should be ~90% of memory limit
    GOMEMLIMIT: 230MiB
    # Pass in the auth user password.
    AUTH_USER_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: nats-auth-credentials
          key: quotedPassword
  # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters.
  # we start with lower resources and monitor over time.
  resources:
    requests:
      cpu: 0.05
      memory: 64Mi
    limits:
      cpu: 0.5
      memory: 256Mi # Adjust GOMEMLIMIT if changing the memory limit.
statefulSet:
  merge:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsNonRoot: true
# Disable NATS Box, it is only required initially to test that the connection is working properly.
# https://github.com/nats-io/nats-box
natsBox:
  enabled: false
# Custom KNIME setting to pass in the password generated by replicated for the auth user.
authUser:
  ## KNIME TODO: Use a generated secret for this.
  password: xodtIzsarf6mbAz7NbPHINDOzpH0IjBf
promExporter:
  podMonitor:
    enabled: false
