####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

resources:
  requests:
    memory: "400Mi"
    cpu: "150m"
  limits:
    memory: "1Gi"
    cpu: "1"
