####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

config:
  builder:
    enableCache: false
    skipTLS: false
    dockerSecrets:
      - regcred
      - knime-hub-registry
    # skipSpecificTLS:
    #   - registry.hub.example.com
