####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

masterCredentials:
  useExistingSecret: true

secrets:
  useExistingSecrets: true

externalPostgres:
  ## For backwards compatibility; creates an ExternalName service.
  ## If you enable this you need to make sure that `.global.postgres.clusters.default.endpoint` is set to knime-postgres-cluster.
  primary:
    enabled: true
    endpoint: some-database-endpoint.region.rds.amazonaws.com
    port: 5432
  ## RDS database certs (for TLS hostname verification): https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesDownload
  rootCert: REPLACE_WITH_BASE64_ENCODED_CERT
