####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

serviceAccount:
  ## only create the role(binding) in the kube-system namespace if ClusterRole provisioning is enabled.
  ## if disabled the user likely does not have permissions to deploy resources to the kube-system namespace.
  createRole: true

## Default setup using KES and storage of secrets in DB backend
config:
  kes:
    enabled: true
    url: "https://secret-store-kes:7373"
    namespace: knime-hub
  s3:
    enabled: false
  vault:
    enabled: false
  ## Override the secret backend to use (`built-in-db` or `built-in-s3` or `built-in-vault`).
  ## Defaults to built-in-db. Secrets in existing installations will be auto-migrated to the backend specified here,
  ## or built-in-db if not specified. This replaces backendDefaultEmptySetup, which only applied to new
  ## installations, but never changed the backend of existing installations.
  secretBackend: built-in-db

## Setup using KES and external S3 storage.
# config:
#   s3:
#     enabled: true
#     bucket: knime-secret-store-service
#     region: us-east-1
#     ## Optional name of Kubernetes secret with `accessKeyId` and `secretAccessKey`,
#     ## otherwise AWS SDK default credential provider chain will be used.
#     secretName: secret-store-minio-secret-store-credentials
#     ## Optional URL of S3 compatible storage, otherwise default AWS S3 endpoint will be used.
#     # url: "http://secret-store-minio:9000"
#   kes:
#     enabled: true
#     url: "https://secret-store-kes:7373"
#     namespace: knime-hub
#   vault:
#     enabled: false
#   secretBackend: built-in-s3
#
## Optional AWS IAM role for service accounts assignment (IRSA),
## used in service-account annotation and the default credentials provider chain to access S3 on AWS.
# aws:
#  serviceAccountRoleArn: arn:aws:iam::1234567890:role/secret-store-role

## Setup using an external Vault storage with KV v2 engine and AppRole auth method.
# config:
#   vault:
#     enabled: true
#     ## URL of Vault.
#     url: http://knime-hub-vault:8200
#     ## Name of Kubernetes secret with `roleId` and `secretId`.
#     secretName: secret-store-vault-credentials
#     ## Mount path of KV engine.
#     mountPath: knime-hub-secret-store
#     ## Optional path of secrets inside the KV engine.
#     # secretPath: /data/secrets
#   kes:
#     enabled: false
#   s3:
#     enabled: false
#   secretBackend: built-in-vault

licenseFile:
  enabled: true
  secretName: "knime-hub-license"
