####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

gateway:
  proxy:
    image: "registry.hubdev.knime.com/knime-hub/istio/proxyv2:1.28.3"
  imagePullSecrets:
    - name: regcred
  name: istio-egressgateway
  labels:
    app: istio-egressgateway
    istio: egressgateway
  autoscaling:
    minReplicas: 3
    maxReplicas: 5
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: null
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: hub.knime.com/role
                operator: In
                values:
                  - core
  tolerations:
    - key: hub.knime.com/role
      value: core
      operator: Equal
      effect: NoSchedule