####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

## This chart is used to generate secrets for KNIME Business Hub, supporting static and generated values.
## All secrets defined in this file should be rotatable (the workload(s) which reference the secrets should be able to adopt new values on pod restart).

secretAnnotations:
  "helm.sh/hook": post-install
  "helm.sh/hook-delete-policy": before-hook-creation
  argocd.argoproj.io/sync-options: Prune=false

secrets:
  # example-secret:
  #   data:
  #     DB_PASSWORD:
  #       generated: true
  #       type: randAlphaNum
  #       length: 32
  #     DB_USERNAME:
  #       generated: false
  #       value: postgres
  accounts-service-listing-api-key:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  accounts-service-account-creation-api-key:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  auth-rely-cookie-secret:
    data:
      hashKey:
        generated: true
        type: randAlphaNum
        length: 64
      blockKey:
        generated: true
        type: randAlphaNum
        length: 32
  catalog-service-content-import-api-key:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  catalog-service-full-read-access-api-key-secret:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  catalog-service-read-disk-storage-api-key-secret:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  catalog-service-catalog-manage-api-key:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  catalog-service-collection-manage-api-key:
    data:
      apiKey:
        generated: true
        type: randAlphaNum
        length: 32
  secret-store-vault-credentials:
    data:
      roleId:
        generated: false
        value: "secret-store"
      secretId:
        generated: true
        type: randAlphaNum
        length: 32
  postgres-backup-minio-credentials:
    data:
      accessKeyId:
        generated: false
        value: postgres-backup
      secretAccessKey:
        generated: true
        type: randAlphaNum
        length: 32
