####################################################################################################
# THIS FILE IS INTENDED TO BE MAINTAINED BY KNIME. SPECIFY OVERRIDES IN THE MAIN VALUES.YAML FILE. #
####################################################################################################

mail:
  enabled: false
  sendAsHtml: true
  ## Set to true if you want to use an existing secret for mail configuration.
  ## Secret needs to have the configuration under a `config` key.
  ## mail.config is ignored if this is set to true.
  useExistingSecret: false
  ## If useExistingSecret is true and existingSecretName is left empty no secret is not mounted.
  ## In this case you need to mount the config yourself using extraVolumes and extraVolumeMounts.
  existingSecretName: ""
  config: |
    mail.from=hub.email@example.com (KNIME Business Hub)
    mail.smtp.host=<host>
    mail.smtp.port=25
    mail.smtp.auth=true
    mail.smtp.user=<user>
    mail.password=<password>
    mail.smtp.starttls.enable=false
    mail.smtp.ssl.enable=false
