apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knime-business-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: knime-business-hub

  source:
    repoURL: https://github.com/btom92/hub
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - local-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
